// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: apps.sql

package db

import (
	"context"
)

const appExistsByName = `-- name: AppExistsByName :one
SELECT EXISTS (SELECT 1 FROM apps WHERE name = ?)
`

func (q *Queries) AppExistsByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, appExistsByName, name)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const clearCrashSuspension = `-- name: ClearCrashSuspension :exec
UPDATE apps SET crash_suspended = 0 WHERE id = ?
`

func (q *Queries) ClearCrashSuspension(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearCrashSuspension, id)
	return err
}

const countAppsByNode = `-- name: CountAppsByNode :many
SELECT node_id, COUNT(*) AS count FROM apps GROUP BY node_id
`

type CountAppsByNodeRow struct {
	NodeID int64
	Count  int64
}

func (q *Queries) CountAppsByNode(ctx context.Context) ([]CountAppsByNodeRow, error) {
	rows, err := q.db.QueryContext(ctx, countAppsByNode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAppsByNodeRow{}
	for rows.Next() {
		var i CountAppsByNodeRow
		if err := rows.Scan(&i.NodeID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createApp = `-- name: CreateApp :one
INSERT INTO apps (name, owner_id, node_id, image, dockerfile, port, env_sealed, memory_mb, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, owner_id, node_id, image, port, env_sealed, running, memory_mb, generation, dns_name, created_at, updated_at, public, logo_mode, logo_color, logo_updated_at, crash_suspended, moving_from, moved_at, dockerfile
`

type CreateAppParams struct {
	Name       string
	OwnerID    int64
	NodeID     int64
	Image      string
	Dockerfile string
	Port       int64
	EnvSealed  string
	MemoryMb   int64
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.db.QueryRowContext(ctx, createApp,
		arg.Name,
		arg.OwnerID,
		arg.NodeID,
		arg.Image,
		arg.Dockerfile,
		arg.Port,
		arg.EnvSealed,
		arg.MemoryMb,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.NodeID,
		&i.Image,
		&i.Port,
		&i.EnvSealed,
		&i.Running,
		&i.MemoryMb,
		&i.Generation,
		&i.DnsName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Public,
		&i.LogoMode,
		&i.LogoColor,
		&i.LogoUpdatedAt,
		&i.CrashSuspended,
		&i.MovingFrom,
		&i.MovedAt,
		&i.Dockerfile,
	)
	return i, err
}

const deleteApp = `-- name: DeleteApp :exec
DELETE FROM apps WHERE id = ?
`

func (q *Queries) DeleteApp(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteApp, id)
	return err
}

const deleteAppLogoImage = `-- name: DeleteAppLogoImage :exec
DELETE FROM app_logos WHERE app_id = ?
`

func (q *Queries) DeleteAppLogoImage(ctx context.Context, appID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAppLogoImage, appID)
	return err
}

const finishMove = `-- name: FinishMove :one
UPDATE apps SET moving_from = 0 WHERE id = ? AND moving_from != 0 RETURNING id, name, owner_id, node_id, image, port, env_sealed, running, memory_mb, generation, dns_name, created_at, updated_at, public, logo_mode, logo_color, logo_updated_at, crash_suspended, moving_from, moved_at, dockerfile
`

func (q *Queries) FinishMove(ctx context.Context, id int64) (App, error) {
	row := q.db.QueryRowContext(ctx, finishMove, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.NodeID,
		&i.Image,
		&i.Port,
		&i.EnvSealed,
		&i.Running,
		&i.MemoryMb,
		&i.Generation,
		&i.DnsName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Public,
		&i.LogoMode,
		&i.LogoColor,
		&i.LogoUpdatedAt,
		&i.CrashSuspended,
		&i.MovingFrom,
		&i.MovedAt,
		&i.Dockerfile,
	)
	return i, err
}

const getApp = `-- name: GetApp :one
SELECT id, name, owner_id, node_id, image, port, env_sealed, running, memory_mb, generation, dns_name, created_at, updated_at, public, logo_mode, logo_color, logo_updated_at, crash_suspended, moving_from, moved_at, dockerfile FROM apps WHERE id = ?
`

func (q *Queries) GetApp(ctx context.Context, id int64) (App, error) {
	row := q.db.QueryRowContext(ctx, getApp, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.NodeID,
		&i.Image,
		&i.Port,
		&i.EnvSealed,
		&i.Running,
		&i.MemoryMb,
		&i.Generation,
		&i.DnsName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Public,
		&i.LogoMode,
		&i.LogoColor,
		&i.LogoUpdatedAt,
		&i.CrashSuspended,
		&i.MovingFrom,
		&i.MovedAt,
		&i.Dockerfile,
	)
	return i, err
}

const getAppLogoImage = `-- name: GetAppLogoImage :one
SELECT app_id, content_type, data FROM app_logos WHERE app_id = ?
`

func (q *Queries) GetAppLogoImage(ctx context.Context, appID int64) (AppLogo, error) {
	row := q.db.QueryRowContext(ctx, getAppLogoImage, appID)
	var i AppLogo
	err := row.Scan(&i.AppID, &i.ContentType, &i.Data)
	return i, err
}

const getImageLogo = `-- name: GetImageLogo :one
SELECT repo, found, content_type, data, fetched_at FROM image_logos WHERE repo = ?
`

func (q *Queries) GetImageLogo(ctx context.Context, repo string) (ImageLogo, error) {
	row := q.db.QueryRowContext(ctx, getImageLogo, repo)
	var i ImageLogo
	err := row.Scan(
		&i.Repo,
		&i.Found,
		&i.ContentType,
		&i.Data,
		&i.FetchedAt,
	)
	return i, err
}

const listApps = `-- name: ListApps :many
SELECT apps.id, apps.name, apps.owner_id, apps.node_id, apps.image, apps.port, apps.env_sealed, apps.running, apps.memory_mb, apps.generation, apps.dns_name, apps.created_at, apps.updated_at, apps.public, apps.logo_mode, apps.logo_color, apps.logo_updated_at, apps.crash_suspended, apps.moving_from, apps.moved_at, apps.dockerfile, users.display_name AS owner_name, users.apps_suspended AS owner_suspended, nodes.name AS node_name
FROM apps
JOIN users ON users.id = apps.owner_id
JOIN nodes ON nodes.id = apps.node_id
ORDER BY apps.name
`

type ListAppsRow struct {
	App            App
	OwnerName      string
	OwnerSuspended int64
	NodeName       string
}

func (q *Queries) ListApps(ctx context.Context) ([]ListAppsRow, error) {
	rows, err := q.db.QueryContext(ctx, listApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppsRow{}
	for rows.Next() {
		var i ListAppsRow
		if err := rows.Scan(
			&i.App.ID,
			&i.App.Name,
			&i.App.OwnerID,
			&i.App.NodeID,
			&i.App.Image,
			&i.App.Port,
			&i.App.EnvSealed,
			&i.App.Running,
			&i.App.MemoryMb,
			&i.App.Generation,
			&i.App.DnsName,
			&i.App.CreatedAt,
			&i.App.UpdatedAt,
			&i.App.Public,
			&i.App.LogoMode,
			&i.App.LogoColor,
			&i.App.LogoUpdatedAt,
			&i.App.CrashSuspended,
			&i.App.MovingFrom,
			&i.App.MovedAt,
			&i.App.Dockerfile,
			&i.OwnerName,
			&i.OwnerSuspended,
			&i.NodeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsByNode = `-- name: ListAppsByNode :many
SELECT id, name, owner_id, node_id, image, port, env_sealed, running, memory_mb, generation, dns_name, created_at, updated_at, public, logo_mode, logo_color, logo_updated_at, crash_suspended, moving_from, moved_at, dockerfile FROM apps WHERE node_id = ? ORDER BY id
`

func (q *Queries) ListAppsByNode(ctx context.Context, nodeID int64) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listAppsByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.NodeID,
			&i.Image,
			&i.Port,
			&i.EnvSealed,
			&i.Running,
			&i.MemoryMb,
			&i.Generation,
			&i.DnsName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Public,
			&i.LogoMode,
			&i.LogoColor,
			&i.LogoUpdatedAt,
			&i.CrashSuspended,
			&i.MovingFrom,
			&i.MovedAt,
			&i.Dockerfile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsByOwner = `-- name: ListAppsByOwner :many
SELECT apps.id, apps.name, apps.owner_id, apps.node_id, apps.image, apps.port, apps.env_sealed, apps.running, apps.memory_mb, apps.generation, apps.dns_name, apps.created_at, apps.updated_at, apps.public, apps.logo_mode, apps.logo_color, apps.logo_updated_at, apps.crash_suspended, apps.moving_from, apps.moved_at, apps.dockerfile, users.display_name AS owner_name, users.apps_suspended AS owner_suspended, nodes.name AS node_name
FROM apps
JOIN users ON users.id = apps.owner_id
JOIN nodes ON nodes.id = apps.node_id
WHERE apps.owner_id = ?
ORDER BY apps.name
`

type ListAppsByOwnerRow struct {
	App            App
	OwnerName      string
	OwnerSuspended int64
	NodeName       string
}

func (q *Queries) ListAppsByOwner(ctx context.Context, ownerID int64) ([]ListAppsByOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, listAppsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppsByOwnerRow{}
	for rows.Next() {
		var i ListAppsByOwnerRow
		if err := rows.Scan(
			&i.App.ID,
			&i.App.Name,
			&i.App.OwnerID,
			&i.App.NodeID,
			&i.App.Image,
			&i.App.Port,
			&i.App.EnvSealed,
			&i.App.Running,
			&i.App.MemoryMb,
			&i.App.Generation,
			&i.App.DnsName,
			&i.App.CreatedAt,
			&i.App.UpdatedAt,
			&i.App.Public,
			&i.App.LogoMode,
			&i.App.LogoColor,
			&i.App.LogoUpdatedAt,
			&i.App.CrashSuspended,
			&i.App.MovingFrom,
			&i.App.MovedAt,
			&i.App.Dockerfile,
			&i.OwnerName,
			&i.OwnerSuspended,
			&i.NodeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsByOwnerID = `-- name: ListAppsByOwnerID :many
SELECT id, name, owner_id, node_id, image, port, env_sealed, running, memory_mb, generation, dns_name, created_at, updated_at, public, logo_mode, logo_color, logo_updated_at, crash_suspended, moving_from, moved_at, dockerfile FROM apps WHERE owner_id = ? ORDER BY id
`

func (q *Queries) ListAppsByOwnerID(ctx context.Context, ownerID int64) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listAppsByOwnerID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.NodeID,
			&i.Image,
			&i.Port,
			&i.EnvSealed,
			&i.Running,
			&i.MemoryMb,
			&i.Generation,
			&i.DnsName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Public,
			&i.LogoMode,
			&i.LogoColor,
			&i.LogoUpdatedAt,
			&i.CrashSuspended,
			&i.MovingFrom,
			&i.MovedAt,
			&i.Dockerfile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsForNode = `-- name: ListAppsForNode :many
SELECT id, name, owner_id, node_id, image, port, env_sealed, running, memory_mb, generation, dns_name, created_at, updated_at, public, logo_mode, logo_color, logo_updated_at, crash_suspended, moving_from, moved_at, dockerfile FROM apps WHERE node_id = ?1 OR moving_from = ?1 ORDER BY id
`

// The apps a node runs: its own, and the ones leaving it for another node.
func (q *Queries) ListAppsForNode(ctx context.Context, nodeID int64) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listAppsForNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.NodeID,
			&i.Image,
			&i.Port,
			&i.EnvSealed,
			&i.Running,
			&i.MemoryMb,
			&i.Generation,
			&i.DnsName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Public,
			&i.LogoMode,
			&i.LogoColor,
			&i.LogoUpdatedAt,
			&i.CrashSuspended,
			&i.MovingFrom,
			&i.MovedAt,
			&i.Dockerfile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicAppsByOwner = `-- name: ListPublicAppsByOwner :many
SELECT id, name, owner_id, node_id, image, port, env_sealed, running, memory_mb, generation, dns_name, created_at, updated_at, public, logo_mode, logo_color, logo_updated_at, crash_suspended, moving_from, moved_at, dockerfile FROM apps WHERE owner_id = ? AND public = 1 ORDER BY name
`

func (q *Queries) ListPublicAppsByOwner(ctx context.Context, ownerID int64) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listPublicAppsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.NodeID,
			&i.Image,
			&i.Port,
			&i.EnvSealed,
			&i.Running,
			&i.MemoryMb,
			&i.Generation,
			&i.DnsName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Public,
			&i.LogoMode,
			&i.LogoColor,
			&i.LogoUpdatedAt,
			&i.CrashSuspended,
			&i.MovingFrom,
			&i.MovedAt,
			&i.Dockerfile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveApp = `-- name: MoveApp :one
UPDATE apps SET moving_from = ?, node_id = ?, moved_at = ?, updated_at = ? WHERE id = ? RETURNING id, name, owner_id, node_id, image, port, env_sealed, running, memory_mb, generation, dns_name, created_at, updated_at, public, logo_mode, logo_color, logo_updated_at, crash_suspended, moving_from, moved_at, dockerfile
`

type MoveAppParams struct {
	MovingFrom int64
	NodeID     int64
	MovedAt    int64
	UpdatedAt  int64
	ID         int64
}

func (q *Queries) MoveApp(ctx context.Context, arg MoveAppParams) (App, error) {
	row := q.db.QueryRowContext(ctx, moveApp,
		arg.MovingFrom,
		arg.NodeID,
		arg.MovedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.NodeID,
		&i.Image,
		&i.Port,
		&i.EnvSealed,
		&i.Running,
		&i.MemoryMb,
		&i.Generation,
		&i.DnsName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Public,
		&i.LogoMode,
		&i.LogoColor,
		&i.LogoUpdatedAt,
		&i.CrashSuspended,
		&i.MovingFrom,
		&i.MovedAt,
		&i.Dockerfile,
	)
	return i, err
}

const putAppLogoImage = `-- name: PutAppLogoImage :exec
INSERT INTO app_logos (app_id, content_type, data) VALUES (?, ?, ?)
ON CONFLICT (app_id) DO UPDATE SET content_type = excluded.content_type, data = excluded.data
`

type PutAppLogoImageParams struct {
	AppID       int64
	ContentType string
	Data        []byte
}

func (q *Queries) PutAppLogoImage(ctx context.Context, arg PutAppLogoImageParams) error {
	_, err := q.db.ExecContext(ctx, putAppLogoImage, arg.AppID, arg.ContentType, arg.Data)
	return err
}

const putImageLogo = `-- name: PutImageLogo :exec
INSERT INTO image_logos (repo, found, content_type, data, fetched_at) VALUES (?, ?, ?, ?, ?)
ON CONFLICT (repo) DO UPDATE SET found = excluded.found, content_type = excluded.content_type,
    data = excluded.data, fetched_at = excluded.fetched_at
`

type PutImageLogoParams struct {
	Repo        string
	Found       int64
	ContentType string
	Data        []byte
	FetchedAt   int64
}

func (q *Queries) PutImageLogo(ctx context.Context, arg PutImageLogoParams) error {
	_, err := q.db.ExecContext(ctx, putImageLogo,
		arg.Repo,
		arg.Found,
		arg.ContentType,
		arg.Data,
		arg.FetchedAt,
	)
	return err
}

const setAppDNSName = `-- name: SetAppDNSName :exec
UPDATE apps SET dns_name = ? WHERE id = ?
`

type SetAppDNSNameParams struct {
	DnsName string
	ID      int64
}

func (q *Queries) SetAppDNSName(ctx context.Context, arg SetAppDNSNameParams) error {
	_, err := q.db.ExecContext(ctx, setAppDNSName, arg.DnsName, arg.ID)
	return err
}

const setAppLogo = `-- name: SetAppLogo :exec
UPDATE apps SET logo_mode = ?, logo_color = ?, logo_updated_at = ? WHERE id = ?
`

type SetAppLogoParams struct {
	LogoMode      string
	LogoColor     string
	LogoUpdatedAt int64
	ID            int64
}

func (q *Queries) SetAppLogo(ctx context.Context, arg SetAppLogoParams) error {
	_, err := q.db.ExecContext(ctx, setAppLogo,
		arg.LogoMode,
		arg.LogoColor,
		arg.LogoUpdatedAt,
		arg.ID,
	)
	return err
}

const setAppPublic = `-- name: SetAppPublic :exec
UPDATE apps SET public = ? WHERE id = ?
`

type SetAppPublicParams struct {
	Public int64
	ID     int64
}

func (q *Queries) SetAppPublic(ctx context.Context, arg SetAppPublicParams) error {
	_, err := q.db.ExecContext(ctx, setAppPublic, arg.Public, arg.ID)
	return err
}

const setAppRunning = `-- name: SetAppRunning :one
UPDATE apps SET running = ?, generation = generation + ?, updated_at = ? WHERE id = ? RETURNING id, name, owner_id, node_id, image, port, env_sealed, running, memory_mb, generation, dns_name, created_at, updated_at, public, logo_mode, logo_color, logo_updated_at, crash_suspended, moving_from, moved_at, dockerfile
`

type SetAppRunningParams struct {
	Running    int64
	Generation int64
	UpdatedAt  int64
	ID         int64
}

func (q *Queries) SetAppRunning(ctx context.Context, arg SetAppRunningParams) (App, error) {
	row := q.db.QueryRowContext(ctx, setAppRunning,
		arg.Running,
		arg.Generation,
		arg.UpdatedAt,
		arg.ID,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.NodeID,
		&i.Image,
		&i.Port,
		&i.EnvSealed,
		&i.Running,
		&i.MemoryMb,
		&i.Generation,
		&i.DnsName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Public,
		&i.LogoMode,
		&i.LogoColor,
		&i.LogoUpdatedAt,
		&i.CrashSuspended,
		&i.MovingFrom,
		&i.MovedAt,
		&i.Dockerfile,
	)
	return i, err
}

const stopAppsByOwner = `-- name: StopAppsByOwner :exec
UPDATE apps SET running = 0, updated_at = ? WHERE owner_id = ?
`

type StopAppsByOwnerParams struct {
	UpdatedAt int64
	OwnerID   int64
}

func (q *Queries) StopAppsByOwner(ctx context.Context, arg StopAppsByOwnerParams) error {
	_, err := q.db.ExecContext(ctx, stopAppsByOwner, arg.UpdatedAt, arg.OwnerID)
	return err
}

const suspendCrashingApp = `-- name: SuspendCrashingApp :one
UPDATE apps SET running = 0, crash_suspended = 1, updated_at = ? WHERE id = ? AND running = 1 RETURNING id, name, owner_id, node_id, image, port, env_sealed, running, memory_mb, generation, dns_name, created_at, updated_at, public, logo_mode, logo_color, logo_updated_at, crash_suspended, moving_from, moved_at, dockerfile
`

type SuspendCrashingAppParams struct {
	UpdatedAt int64
	ID        int64
}

func (q *Queries) SuspendCrashingApp(ctx context.Context, arg SuspendCrashingAppParams) (App, error) {
	row := q.db.QueryRowContext(ctx, suspendCrashingApp, arg.UpdatedAt, arg.ID)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.NodeID,
		&i.Image,
		&i.Port,
		&i.EnvSealed,
		&i.Running,
		&i.MemoryMb,
		&i.Generation,
		&i.DnsName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Public,
		&i.LogoMode,
		&i.LogoColor,
		&i.LogoUpdatedAt,
		&i.CrashSuspended,
		&i.MovingFrom,
		&i.MovedAt,
		&i.Dockerfile,
	)
	return i, err
}

const updateAppConfig = `-- name: UpdateAppConfig :one
UPDATE apps SET image = ?, dockerfile = ?, port = ?, env_sealed = ?, memory_mb = ?, generation = generation + 1, updated_at = ?
WHERE id = ?
RETURNING id, name, owner_id, node_id, image, port, env_sealed, running, memory_mb, generation, dns_name, created_at, updated_at, public, logo_mode, logo_color, logo_updated_at, crash_suspended, moving_from, moved_at, dockerfile
`

type UpdateAppConfigParams struct {
	Image      string
	Dockerfile string
	Port       int64
	EnvSealed  string
	MemoryMb   int64
	UpdatedAt  int64
	ID         int64
}

func (q *Queries) UpdateAppConfig(ctx context.Context, arg UpdateAppConfigParams) (App, error) {
	row := q.db.QueryRowContext(ctx, updateAppConfig,
		arg.Image,
		arg.Dockerfile,
		arg.Port,
		arg.EnvSealed,
		arg.MemoryMb,
		arg.UpdatedAt,
		arg.ID,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.NodeID,
		&i.Image,
		&i.Port,
		&i.EnvSealed,
		&i.Running,
		&i.MemoryMb,
		&i.Generation,
		&i.DnsName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Public,
		&i.LogoMode,
		&i.LogoColor,
		&i.LogoUpdatedAt,
		&i.CrashSuspended,
		&i.MovingFrom,
		&i.MovedAt,
		&i.Dockerfile,
	)
	return i, err
}

const updateNodeIngress = `-- name: UpdateNodeIngress :one
UPDATE nodes SET public_ip = ?, ingress_mode = ?, ingress_http_port = ? WHERE id = ? RETURNING id, name, status, join_token_hash, join_expires_at, cert_serial, hostname, os, arch, cpus, memory_bytes, disk_bytes, docker_version, agent_version, last_seen_at, created_at, public_ip, ingress_mode, ingress_http_port, is_local, local_ip, docker_error
`

type UpdateNodeIngressParams struct {
	PublicIp        string
	IngressMode     string
	IngressHttpPort int64
	ID              int64
}

func (q *Queries) UpdateNodeIngress(ctx context.Context, arg UpdateNodeIngressParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, updateNodeIngress,
		arg.PublicIp,
		arg.IngressMode,
		arg.IngressHttpPort,
		arg.ID,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.JoinTokenHash,
		&i.JoinExpiresAt,
		&i.CertSerial,
		&i.Hostname,
		&i.Os,
		&i.Arch,
		&i.Cpus,
		&i.MemoryBytes,
		&i.DiskBytes,
		&i.DockerVersion,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.PublicIp,
		&i.IngressMode,
		&i.IngressHttpPort,
		&i.IsLocal,
		&i.LocalIp,
		&i.DockerError,
	)
	return i, err
}
