// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: apps.sql

package db

import (
	"context"
)

const appExistsByName = `-- name: AppExistsByName :one
SELECT EXISTS (SELECT 1 FROM apps WHERE name = ?)
`

func (q *Queries) AppExistsByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, appExistsByName, name)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countAppsByNode = `-- name: CountAppsByNode :many
SELECT node_id, COUNT(*) AS count FROM apps GROUP BY node_id
`

type CountAppsByNodeRow struct {
	NodeID int64
	Count  int64
}

func (q *Queries) CountAppsByNode(ctx context.Context) ([]CountAppsByNodeRow, error) {
	rows, err := q.db.QueryContext(ctx, countAppsByNode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAppsByNodeRow{}
	for rows.Next() {
		var i CountAppsByNodeRow
		if err := rows.Scan(&i.NodeID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createApp = `-- name: CreateApp :one
INSERT INTO apps (name, owner_id, node_id, image, port, env_sealed, memory_mb, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, owner_id, node_id, image, port, env_sealed, running, memory_mb, generation, dns_name, created_at, updated_at
`

type CreateAppParams struct {
	Name      string
	OwnerID   int64
	NodeID    int64
	Image     string
	Port      int64
	EnvSealed string
	MemoryMb  int64
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.db.QueryRowContext(ctx, createApp,
		arg.Name,
		arg.OwnerID,
		arg.NodeID,
		arg.Image,
		arg.Port,
		arg.EnvSealed,
		arg.MemoryMb,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.NodeID,
		&i.Image,
		&i.Port,
		&i.EnvSealed,
		&i.Running,
		&i.MemoryMb,
		&i.Generation,
		&i.DnsName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApp = `-- name: DeleteApp :exec
DELETE FROM apps WHERE id = ?
`

func (q *Queries) DeleteApp(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteApp, id)
	return err
}

const getApp = `-- name: GetApp :one
SELECT id, name, owner_id, node_id, image, port, env_sealed, running, memory_mb, generation, dns_name, created_at, updated_at FROM apps WHERE id = ?
`

func (q *Queries) GetApp(ctx context.Context, id int64) (App, error) {
	row := q.db.QueryRowContext(ctx, getApp, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.NodeID,
		&i.Image,
		&i.Port,
		&i.EnvSealed,
		&i.Running,
		&i.MemoryMb,
		&i.Generation,
		&i.DnsName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApps = `-- name: ListApps :many
SELECT apps.id, apps.name, apps.owner_id, apps.node_id, apps.image, apps.port, apps.env_sealed, apps.running, apps.memory_mb, apps.generation, apps.dns_name, apps.created_at, apps.updated_at, users.display_name AS owner_name, users.apps_suspended AS owner_suspended, nodes.name AS node_name
FROM apps
JOIN users ON users.id = apps.owner_id
JOIN nodes ON nodes.id = apps.node_id
ORDER BY apps.name
`

type ListAppsRow struct {
	ID             int64
	Name           string
	OwnerID        int64
	NodeID         int64
	Image          string
	Port           int64
	EnvSealed      string
	Running        int64
	MemoryMb       int64
	Generation     int64
	DnsName        string
	CreatedAt      int64
	UpdatedAt      int64
	OwnerName      string
	OwnerSuspended int64
	NodeName       string
}

func (q *Queries) ListApps(ctx context.Context) ([]ListAppsRow, error) {
	rows, err := q.db.QueryContext(ctx, listApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppsRow{}
	for rows.Next() {
		var i ListAppsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.NodeID,
			&i.Image,
			&i.Port,
			&i.EnvSealed,
			&i.Running,
			&i.MemoryMb,
			&i.Generation,
			&i.DnsName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.OwnerSuspended,
			&i.NodeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsByNode = `-- name: ListAppsByNode :many
SELECT id, name, owner_id, node_id, image, port, env_sealed, running, memory_mb, generation, dns_name, created_at, updated_at FROM apps WHERE node_id = ? ORDER BY id
`

func (q *Queries) ListAppsByNode(ctx context.Context, nodeID int64) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listAppsByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.NodeID,
			&i.Image,
			&i.Port,
			&i.EnvSealed,
			&i.Running,
			&i.MemoryMb,
			&i.Generation,
			&i.DnsName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsByOwner = `-- name: ListAppsByOwner :many
SELECT apps.id, apps.name, apps.owner_id, apps.node_id, apps.image, apps.port, apps.env_sealed, apps.running, apps.memory_mb, apps.generation, apps.dns_name, apps.created_at, apps.updated_at, users.display_name AS owner_name, users.apps_suspended AS owner_suspended, nodes.name AS node_name
FROM apps
JOIN users ON users.id = apps.owner_id
JOIN nodes ON nodes.id = apps.node_id
WHERE apps.owner_id = ?
ORDER BY apps.name
`

type ListAppsByOwnerRow struct {
	ID             int64
	Name           string
	OwnerID        int64
	NodeID         int64
	Image          string
	Port           int64
	EnvSealed      string
	Running        int64
	MemoryMb       int64
	Generation     int64
	DnsName        string
	CreatedAt      int64
	UpdatedAt      int64
	OwnerName      string
	OwnerSuspended int64
	NodeName       string
}

func (q *Queries) ListAppsByOwner(ctx context.Context, ownerID int64) ([]ListAppsByOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, listAppsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppsByOwnerRow{}
	for rows.Next() {
		var i ListAppsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.NodeID,
			&i.Image,
			&i.Port,
			&i.EnvSealed,
			&i.Running,
			&i.MemoryMb,
			&i.Generation,
			&i.DnsName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.OwnerSuspended,
			&i.NodeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsByOwnerID = `-- name: ListAppsByOwnerID :many
SELECT id, name, owner_id, node_id, image, port, env_sealed, running, memory_mb, generation, dns_name, created_at, updated_at FROM apps WHERE owner_id = ? ORDER BY id
`

func (q *Queries) ListAppsByOwnerID(ctx context.Context, ownerID int64) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listAppsByOwnerID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.NodeID,
			&i.Image,
			&i.Port,
			&i.EnvSealed,
			&i.Running,
			&i.MemoryMb,
			&i.Generation,
			&i.DnsName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAppDNSName = `-- name: SetAppDNSName :exec
UPDATE apps SET dns_name = ? WHERE id = ?
`

type SetAppDNSNameParams struct {
	DnsName string
	ID      int64
}

func (q *Queries) SetAppDNSName(ctx context.Context, arg SetAppDNSNameParams) error {
	_, err := q.db.ExecContext(ctx, setAppDNSName, arg.DnsName, arg.ID)
	return err
}

const setAppRunning = `-- name: SetAppRunning :one
UPDATE apps SET running = ?, generation = generation + ?, updated_at = ? WHERE id = ? RETURNING id, name, owner_id, node_id, image, port, env_sealed, running, memory_mb, generation, dns_name, created_at, updated_at
`

type SetAppRunningParams struct {
	Running    int64
	Generation int64
	UpdatedAt  int64
	ID         int64
}

func (q *Queries) SetAppRunning(ctx context.Context, arg SetAppRunningParams) (App, error) {
	row := q.db.QueryRowContext(ctx, setAppRunning,
		arg.Running,
		arg.Generation,
		arg.UpdatedAt,
		arg.ID,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.NodeID,
		&i.Image,
		&i.Port,
		&i.EnvSealed,
		&i.Running,
		&i.MemoryMb,
		&i.Generation,
		&i.DnsName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const stopAppsByOwner = `-- name: StopAppsByOwner :exec
UPDATE apps SET running = 0, updated_at = ? WHERE owner_id = ?
`

type StopAppsByOwnerParams struct {
	UpdatedAt int64
	OwnerID   int64
}

func (q *Queries) StopAppsByOwner(ctx context.Context, arg StopAppsByOwnerParams) error {
	_, err := q.db.ExecContext(ctx, stopAppsByOwner, arg.UpdatedAt, arg.OwnerID)
	return err
}

const updateAppConfig = `-- name: UpdateAppConfig :one
UPDATE apps SET image = ?, port = ?, env_sealed = ?, memory_mb = ?, generation = generation + 1, updated_at = ?
WHERE id = ?
RETURNING id, name, owner_id, node_id, image, port, env_sealed, running, memory_mb, generation, dns_name, created_at, updated_at
`

type UpdateAppConfigParams struct {
	Image     string
	Port      int64
	EnvSealed string
	MemoryMb  int64
	UpdatedAt int64
	ID        int64
}

func (q *Queries) UpdateAppConfig(ctx context.Context, arg UpdateAppConfigParams) (App, error) {
	row := q.db.QueryRowContext(ctx, updateAppConfig,
		arg.Image,
		arg.Port,
		arg.EnvSealed,
		arg.MemoryMb,
		arg.UpdatedAt,
		arg.ID,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.NodeID,
		&i.Image,
		&i.Port,
		&i.EnvSealed,
		&i.Running,
		&i.MemoryMb,
		&i.Generation,
		&i.DnsName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNodeIngress = `-- name: UpdateNodeIngress :one
UPDATE nodes SET public_ip = ?, ingress_mode = ?, ingress_http_port = ? WHERE id = ? RETURNING id, name, status, join_token_hash, join_expires_at, cert_serial, hostname, os, arch, cpus, memory_bytes, disk_bytes, docker_version, agent_version, last_seen_at, created_at, public_ip, ingress_mode, ingress_http_port, is_local, local_ip
`

type UpdateNodeIngressParams struct {
	PublicIp        string
	IngressMode     string
	IngressHttpPort int64
	ID              int64
}

func (q *Queries) UpdateNodeIngress(ctx context.Context, arg UpdateNodeIngressParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, updateNodeIngress,
		arg.PublicIp,
		arg.IngressMode,
		arg.IngressHttpPort,
		arg.ID,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.JoinTokenHash,
		&i.JoinExpiresAt,
		&i.CertSerial,
		&i.Hostname,
		&i.Os,
		&i.Arch,
		&i.Cpus,
		&i.MemoryBytes,
		&i.DiskBytes,
		&i.DockerVersion,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.PublicIp,
		&i.IngressMode,
		&i.IngressHttpPort,
		&i.IsLocal,
		&i.LocalIp,
	)
	return i, err
}
