// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: events.sql

package db

import (
	"context"
)

const addAppEvent = `-- name: AddAppEvent :exec
INSERT INTO app_events (app_id, at, kind, message) VALUES (?, ?, ?, ?)
`

type AddAppEventParams struct {
	AppID   int64
	At      int64
	Kind    string
	Message string
}

func (q *Queries) AddAppEvent(ctx context.Context, arg AddAppEventParams) error {
	_, err := q.db.ExecContext(ctx, addAppEvent,
		arg.AppID,
		arg.At,
		arg.Kind,
		arg.Message,
	)
	return err
}

const listAppEvents = `-- name: ListAppEvents :many
SELECT id, app_id, at, kind, message FROM app_events WHERE app_id = ? ORDER BY id DESC LIMIT ?
`

type ListAppEventsParams struct {
	AppID int64
	Limit int64
}

func (q *Queries) ListAppEvents(ctx context.Context, arg ListAppEventsParams) ([]AppEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAppEvents, arg.AppID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppEvent{}
	for rows.Next() {
		var i AppEvent
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.At,
			&i.Kind,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAppEvents = `-- name: PruneAppEvents :exec
DELETE FROM app_events
WHERE app_events.app_id = ?1
  AND app_events.id NOT IN (SELECT e.id FROM app_events e WHERE e.app_id = ?1 ORDER BY e.id DESC LIMIT 200)
`

func (q *Queries) PruneAppEvents(ctx context.Context, appID int64) error {
	_, err := q.db.ExecContext(ctx, pruneAppEvents, appID)
	return err
}
