// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: login_links.sql

package db

import (
	"context"
)

const consumeLoginLink = `-- name: ConsumeLoginLink :one
DELETE FROM login_links WHERE token_hash = ? AND expires_at > ? RETURNING user_id
`

type ConsumeLoginLinkParams struct {
	TokenHash string
	ExpiresAt int64
}

func (q *Queries) ConsumeLoginLink(ctx context.Context, arg ConsumeLoginLinkParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, consumeLoginLink, arg.TokenHash, arg.ExpiresAt)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const createLoginLink = `-- name: CreateLoginLink :exec
INSERT INTO login_links (token_hash, user_id, expires_at) VALUES (?, ?, ?)
`

type CreateLoginLinkParams struct {
	TokenHash string
	UserID    int64
	ExpiresAt int64
}

func (q *Queries) CreateLoginLink(ctx context.Context, arg CreateLoginLinkParams) error {
	_, err := q.db.ExecContext(ctx, createLoginLink, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteExpiredLoginLinks = `-- name: DeleteExpiredLoginLinks :exec
DELETE FROM login_links WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredLoginLinks(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredLoginLinks, expiresAt)
	return err
}
