// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type AccountRequest struct {
	ID          int64
	DiscordID   string
	Username    string
	DisplayName string
	Email       sql.NullString
	Avatar      sql.NullString
	Status      string
	Reason      sql.NullString
	CreatedAt   int64
	DecidedAt   sql.NullInt64
}

type App struct {
	ID             int64
	Name           string
	OwnerID        int64
	NodeID         int64
	Image          string
	Port           int64
	EnvSealed      string
	Running        int64
	MemoryMb       int64
	Generation     int64
	DnsName        string
	CreatedAt      int64
	UpdatedAt      int64
	Public         int64
	LogoMode       string
	LogoColor      string
	LogoUpdatedAt  int64
	CrashSuspended int64
	MovingFrom     int64
	MovedAt        int64
	Dockerfile     string
	Kind           string
	PortSource     string
}

type AppEvent struct {
	ID      int64
	AppID   int64
	At      int64
	Kind    string
	Message string
}

type AppLogo struct {
	AppID       int64
	ContentType string
	Data        []byte
}

type Avatar struct {
	UserID      int64
	ContentType string
	Data        []byte
}

type Banner struct {
	UserID      int64
	ContentType string
	Data        []byte
}

type ContainerEvent struct {
	ID      int64
	NodeID  int64
	Name    string
	At      int64
	Kind    string
	Message string
}

type ImageLogo struct {
	Repo        string
	Found       int64
	ContentType string
	Data        []byte
	FetchedAt   int64
}

type InstanceIcon struct {
	ID          int64
	ContentType string
	Data        []byte
	UpdatedAt   int64
}

type LoginLink struct {
	TokenHash string
	UserID    int64
	ExpiresAt int64
}

type Node struct {
	ID              int64
	Name            string
	Status          string
	JoinTokenHash   sql.NullString
	JoinExpiresAt   sql.NullInt64
	CertSerial      sql.NullString
	Hostname        string
	Os              string
	Arch            string
	Cpus            int64
	MemoryBytes     int64
	DiskBytes       int64
	DockerVersion   string
	AgentVersion    string
	LastSeenAt      sql.NullInt64
	CreatedAt       int64
	PublicIp        string
	IngressMode     string
	IngressHttpPort int64
	IsLocal         int64
	LocalIp         string
	DockerError     string
}

type Session struct {
	TokenHash string
	UserID    int64
	CreatedAt int64
	ExpiresAt int64
	Ip        string
	UserAgent string
}

type Setting struct {
	Key   string
	Value string
}

type SshKey struct {
	ID          int64
	UserID      int64
	Name        string
	PublicKey   string
	Fingerprint string
	CreatedAt   int64
	LastUsedAt  int64
}

type SupportMessage struct {
	ID        int64
	TicketID  int64
	AuthorID  sql.NullInt64
	Body      string
	CreatedAt int64
}

type SupportTicket struct {
	ID        int64
	AuthorID  int64
	Kind      string
	AppID     sql.NullInt64
	AppName   string
	Subject   string
	Status    string
	Waiting   int64
	CreatedAt int64
	UpdatedAt int64
}

type User struct {
	ID              int64
	Username        sql.NullString
	PasswordHash    sql.NullString
	DiscordID       sql.NullString
	DisplayName     string
	Role            string
	Disabled        int64
	CreatedAt       int64
	Email           sql.NullString
	AppsSuspended   int64
	DiscordName     string
	DiscordAvatar   string
	NameFromDiscord int64
	Bio             string
	AvatarUpdatedAt int64
	DiscordBanner   string
	DiscordAccent   int64
	BannerUpdatedAt int64
	ShowApps        int64
	ShowEmail       int64
	NotifyWebhook   string
}
