// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type AccountRequest struct {
	ID          int64
	DiscordID   string
	Username    string
	DisplayName string
	Email       sql.NullString
	Avatar      sql.NullString
	Status      string
	Reason      sql.NullString
	CreatedAt   int64
	DecidedAt   sql.NullInt64
}

type Session struct {
	TokenHash string
	UserID    int64
	CreatedAt int64
	ExpiresAt int64
}

type Setting struct {
	Key   string
	Value string
}

type User struct {
	ID           int64
	Username     sql.NullString
	PasswordHash sql.NullString
	DiscordID    sql.NullString
	DisplayName  string
	Role         string
	Disabled     int64
	CreatedAt    int64
	Email        sql.NullString
}
