// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type AccountRequest struct {
	ID          int64
	DiscordID   string
	Username    string
	DisplayName string
	Email       sql.NullString
	Avatar      sql.NullString
	Status      string
	Reason      sql.NullString
	CreatedAt   int64
	DecidedAt   sql.NullInt64
}

type App struct {
	ID         int64
	Name       string
	OwnerID    int64
	NodeID     int64
	Image      string
	Port       int64
	EnvSealed  string
	Running    int64
	MemoryMb   int64
	Generation int64
	DnsName    string
	CreatedAt  int64
	UpdatedAt  int64
}

type LoginLink struct {
	TokenHash string
	UserID    int64
	ExpiresAt int64
}

type Node struct {
	ID              int64
	Name            string
	Status          string
	JoinTokenHash   sql.NullString
	JoinExpiresAt   sql.NullInt64
	CertSerial      sql.NullString
	Hostname        string
	Os              string
	Arch            string
	Cpus            int64
	MemoryBytes     int64
	DiskBytes       int64
	DockerVersion   string
	AgentVersion    string
	LastSeenAt      sql.NullInt64
	CreatedAt       int64
	PublicIp        string
	IngressMode     string
	IngressHttpPort int64
}

type Session struct {
	TokenHash string
	UserID    int64
	CreatedAt int64
	ExpiresAt int64
}

type Setting struct {
	Key   string
	Value string
}

type User struct {
	ID           int64
	Username     sql.NullString
	PasswordHash sql.NullString
	DiscordID    sql.NullString
	DisplayName  string
	Role         string
	Disabled     int64
	CreatedAt    int64
	Email        sql.NullString
}
