// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: nodes.sql

package db

import (
	"context"
	"database/sql"
)

const activateNode = `-- name: ActivateNode :exec
UPDATE nodes SET status = 'active', cert_serial = ?, join_token_hash = NULL, join_expires_at = NULL
WHERE id = ? AND status = 'pending'
`

type ActivateNodeParams struct {
	CertSerial sql.NullString
	ID         int64
}

func (q *Queries) ActivateNode(ctx context.Context, arg ActivateNodeParams) error {
	_, err := q.db.ExecContext(ctx, activateNode, arg.CertSerial, arg.ID)
	return err
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (name, status, join_token_hash, join_expires_at, is_local, created_at)
VALUES (?, 'pending', ?, ?, ?, ?)
RETURNING id, name, status, join_token_hash, join_expires_at, cert_serial, hostname, os, arch, cpus, memory_bytes, disk_bytes, docker_version, agent_version, last_seen_at, created_at, public_ip, ingress_mode, ingress_http_port, is_local, local_ip, docker_error
`

type CreateNodeParams struct {
	Name          string
	JoinTokenHash sql.NullString
	JoinExpiresAt sql.NullInt64
	IsLocal       int64
	CreatedAt     int64
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, createNode,
		arg.Name,
		arg.JoinTokenHash,
		arg.JoinExpiresAt,
		arg.IsLocal,
		arg.CreatedAt,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.JoinTokenHash,
		&i.JoinExpiresAt,
		&i.CertSerial,
		&i.Hostname,
		&i.Os,
		&i.Arch,
		&i.Cpus,
		&i.MemoryBytes,
		&i.DiskBytes,
		&i.DockerVersion,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.PublicIp,
		&i.IngressMode,
		&i.IngressHttpPort,
		&i.IsLocal,
		&i.LocalIp,
		&i.DockerError,
	)
	return i, err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE id = ?
`

func (q *Queries) DeleteNode(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNode, id)
	return err
}

const getLocalNode = `-- name: GetLocalNode :one
SELECT id, name, status, join_token_hash, join_expires_at, cert_serial, hostname, os, arch, cpus, memory_bytes, disk_bytes, docker_version, agent_version, last_seen_at, created_at, public_ip, ingress_mode, ingress_http_port, is_local, local_ip, docker_error FROM nodes WHERE is_local = 1 LIMIT 1
`

func (q *Queries) GetLocalNode(ctx context.Context) (Node, error) {
	row := q.db.QueryRowContext(ctx, getLocalNode)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.JoinTokenHash,
		&i.JoinExpiresAt,
		&i.CertSerial,
		&i.Hostname,
		&i.Os,
		&i.Arch,
		&i.Cpus,
		&i.MemoryBytes,
		&i.DiskBytes,
		&i.DockerVersion,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.PublicIp,
		&i.IngressMode,
		&i.IngressHttpPort,
		&i.IsLocal,
		&i.LocalIp,
		&i.DockerError,
	)
	return i, err
}

const getNode = `-- name: GetNode :one
SELECT id, name, status, join_token_hash, join_expires_at, cert_serial, hostname, os, arch, cpus, memory_bytes, disk_bytes, docker_version, agent_version, last_seen_at, created_at, public_ip, ingress_mode, ingress_http_port, is_local, local_ip, docker_error FROM nodes WHERE id = ?
`

func (q *Queries) GetNode(ctx context.Context, id int64) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.JoinTokenHash,
		&i.JoinExpiresAt,
		&i.CertSerial,
		&i.Hostname,
		&i.Os,
		&i.Arch,
		&i.Cpus,
		&i.MemoryBytes,
		&i.DiskBytes,
		&i.DockerVersion,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.PublicIp,
		&i.IngressMode,
		&i.IngressHttpPort,
		&i.IsLocal,
		&i.LocalIp,
		&i.DockerError,
	)
	return i, err
}

const getPendingNodeByJoinToken = `-- name: GetPendingNodeByJoinToken :one
SELECT id, name, status, join_token_hash, join_expires_at, cert_serial, hostname, os, arch, cpus, memory_bytes, disk_bytes, docker_version, agent_version, last_seen_at, created_at, public_ip, ingress_mode, ingress_http_port, is_local, local_ip, docker_error FROM nodes WHERE join_token_hash = ? AND status = 'pending' AND join_expires_at > ?
`

type GetPendingNodeByJoinTokenParams struct {
	JoinTokenHash sql.NullString
	JoinExpiresAt sql.NullInt64
}

func (q *Queries) GetPendingNodeByJoinToken(ctx context.Context, arg GetPendingNodeByJoinTokenParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, getPendingNodeByJoinToken, arg.JoinTokenHash, arg.JoinExpiresAt)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.JoinTokenHash,
		&i.JoinExpiresAt,
		&i.CertSerial,
		&i.Hostname,
		&i.Os,
		&i.Arch,
		&i.Cpus,
		&i.MemoryBytes,
		&i.DiskBytes,
		&i.DockerVersion,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.PublicIp,
		&i.IngressMode,
		&i.IngressHttpPort,
		&i.IsLocal,
		&i.LocalIp,
		&i.DockerError,
	)
	return i, err
}

const hasLocalNode = `-- name: HasLocalNode :one
SELECT EXISTS (SELECT 1 FROM nodes WHERE is_local = 1)
`

func (q *Queries) HasLocalNode(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasLocalNode)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listNodes = `-- name: ListNodes :many
SELECT id, name, status, join_token_hash, join_expires_at, cert_serial, hostname, os, arch, cpus, memory_bytes, disk_bytes, docker_version, agent_version, last_seen_at, created_at, public_ip, ingress_mode, ingress_http_port, is_local, local_ip, docker_error FROM nodes ORDER BY name
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.JoinTokenHash,
			&i.JoinExpiresAt,
			&i.CertSerial,
			&i.Hostname,
			&i.Os,
			&i.Arch,
			&i.Cpus,
			&i.MemoryBytes,
			&i.DiskBytes,
			&i.DockerVersion,
			&i.AgentVersion,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.PublicIp,
			&i.IngressMode,
			&i.IngressHttpPort,
			&i.IsLocal,
			&i.LocalIp,
			&i.DockerError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetNodeJoinToken = `-- name: ResetNodeJoinToken :exec
UPDATE nodes SET join_token_hash = ?, join_expires_at = ? WHERE id = ? AND status = 'pending'
`

type ResetNodeJoinTokenParams struct {
	JoinTokenHash sql.NullString
	JoinExpiresAt sql.NullInt64
	ID            int64
}

func (q *Queries) ResetNodeJoinToken(ctx context.Context, arg ResetNodeJoinTokenParams) error {
	_, err := q.db.ExecContext(ctx, resetNodeJoinToken, arg.JoinTokenHash, arg.JoinExpiresAt, arg.ID)
	return err
}

const touchNode = `-- name: TouchNode :exec
UPDATE nodes SET last_seen_at = ? WHERE id = ?
`

type TouchNodeParams struct {
	LastSeenAt sql.NullInt64
	ID         int64
}

func (q *Queries) TouchNode(ctx context.Context, arg TouchNodeParams) error {
	_, err := q.db.ExecContext(ctx, touchNode, arg.LastSeenAt, arg.ID)
	return err
}

const updateNodeInfo = `-- name: UpdateNodeInfo :exec
UPDATE nodes
SET hostname = ?, os = ?, arch = ?, cpus = ?, memory_bytes = ?, disk_bytes = ?,
    docker_version = ?, docker_error = ?, agent_version = ?, local_ip = ?, last_seen_at = ?
WHERE id = ?
`

type UpdateNodeInfoParams struct {
	Hostname      string
	Os            string
	Arch          string
	Cpus          int64
	MemoryBytes   int64
	DiskBytes     int64
	DockerVersion string
	DockerError   string
	AgentVersion  string
	LocalIp       string
	LastSeenAt    sql.NullInt64
	ID            int64
}

func (q *Queries) UpdateNodeInfo(ctx context.Context, arg UpdateNodeInfoParams) error {
	_, err := q.db.ExecContext(ctx, updateNodeInfo,
		arg.Hostname,
		arg.Os,
		arg.Arch,
		arg.Cpus,
		arg.MemoryBytes,
		arg.DiskBytes,
		arg.DockerVersion,
		arg.DockerError,
		arg.AgentVersion,
		arg.LocalIp,
		arg.LastSeenAt,
		arg.ID,
	)
	return err
}
