// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: requests.sql

package db

import (
	"context"
	"database/sql"
)

const createAccountRequest = `-- name: CreateAccountRequest :one
INSERT INTO account_requests (discord_id, username, display_name, email, avatar, status, created_at)
VALUES (?, ?, ?, ?, ?, 'pending', ?)
RETURNING id, discord_id, username, display_name, email, avatar, status, reason, created_at, decided_at
`

type CreateAccountRequestParams struct {
	DiscordID   string
	Username    string
	DisplayName string
	Email       sql.NullString
	Avatar      sql.NullString
	CreatedAt   int64
}

func (q *Queries) CreateAccountRequest(ctx context.Context, arg CreateAccountRequestParams) (AccountRequest, error) {
	row := q.db.QueryRowContext(ctx, createAccountRequest,
		arg.DiscordID,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.Avatar,
		arg.CreatedAt,
	)
	var i AccountRequest
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Avatar,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const deleteAccountRequest = `-- name: DeleteAccountRequest :exec
DELETE FROM account_requests WHERE id = ?
`

func (q *Queries) DeleteAccountRequest(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccountRequest, id)
	return err
}

const getAccountRequest = `-- name: GetAccountRequest :one
SELECT id, discord_id, username, display_name, email, avatar, status, reason, created_at, decided_at FROM account_requests WHERE id = ?
`

func (q *Queries) GetAccountRequest(ctx context.Context, id int64) (AccountRequest, error) {
	row := q.db.QueryRowContext(ctx, getAccountRequest, id)
	var i AccountRequest
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Avatar,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getAccountRequestByDiscordID = `-- name: GetAccountRequestByDiscordID :one
SELECT id, discord_id, username, display_name, email, avatar, status, reason, created_at, decided_at FROM account_requests WHERE discord_id = ?
`

func (q *Queries) GetAccountRequestByDiscordID(ctx context.Context, discordID string) (AccountRequest, error) {
	row := q.db.QueryRowContext(ctx, getAccountRequestByDiscordID, discordID)
	var i AccountRequest
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Avatar,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const listPendingAccountRequests = `-- name: ListPendingAccountRequests :many
SELECT id, discord_id, username, display_name, email, avatar, status, reason, created_at, decided_at FROM account_requests WHERE status = 'pending' ORDER BY created_at
`

func (q *Queries) ListPendingAccountRequests(ctx context.Context) ([]AccountRequest, error) {
	rows, err := q.db.QueryContext(ctx, listPendingAccountRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountRequest{}
	for rows.Next() {
		var i AccountRequest
		if err := rows.Scan(
			&i.ID,
			&i.DiscordID,
			&i.Username,
			&i.DisplayName,
			&i.Email,
			&i.Avatar,
			&i.Status,
			&i.Reason,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refuseAccountRequest = `-- name: RefuseAccountRequest :exec
UPDATE account_requests SET status = 'refused', reason = ?, decided_at = ? WHERE id = ? AND status = 'pending'
`

type RefuseAccountRequestParams struct {
	Reason    sql.NullString
	DecidedAt sql.NullInt64
	ID        int64
}

func (q *Queries) RefuseAccountRequest(ctx context.Context, arg RefuseAccountRequestParams) error {
	_, err := q.db.ExecContext(ctx, refuseAccountRequest, arg.Reason, arg.DecidedAt, arg.ID)
	return err
}

const updateAccountRequestProfile = `-- name: UpdateAccountRequestProfile :exec
UPDATE account_requests SET username = ?, display_name = ?, email = ?, avatar = ? WHERE id = ?
`

type UpdateAccountRequestProfileParams struct {
	Username    string
	DisplayName string
	Email       sql.NullString
	Avatar      sql.NullString
	ID          int64
}

func (q *Queries) UpdateAccountRequestProfile(ctx context.Context, arg UpdateAccountRequestProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountRequestProfile,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.Avatar,
		arg.ID,
	)
	return err
}
