// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, created_at, expires_at, ip, user_agent)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	TokenHash string
	UserID    int64
	CreatedAt int64
	ExpiresAt int64
	Ip        string
	UserAgent string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteOtherSessions = `-- name: DeleteOtherSessions :exec
DELETE FROM sessions WHERE user_id = ? AND token_hash != ?
`

type DeleteOtherSessionsParams struct {
	UserID    int64
	TokenHash string
}

func (q *Queries) DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteOtherSessions, arg.UserID, arg.TokenHash)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const deleteUserSession = `-- name: DeleteUserSession :exec
DELETE FROM sessions WHERE user_id = ? AND token_hash = ?
`

type DeleteUserSessionParams struct {
	UserID    int64
	TokenHash string
}

func (q *Queries) DeleteUserSession(ctx context.Context, arg DeleteUserSessionParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserSession, arg.UserID, arg.TokenHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT users.id, users.username, users.password_hash, users.discord_id, users.display_name, users.role, users.disabled, users.created_at, users.email, users.apps_suspended, users.discord_name, users.discord_avatar, users.name_from_discord, users.bio, users.avatar_updated_at, users.discord_banner, users.discord_accent, users.banner_updated_at, users.show_apps, users.show_email, users.notify_webhook
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = ? AND sessions.expires_at > ? AND users.disabled = 0
`

type GetSessionUserParams struct {
	TokenHash string
	ExpiresAt int64
}

func (q *Queries) GetSessionUser(ctx context.Context, arg GetSessionUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getSessionUser, arg.TokenHash, arg.ExpiresAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DiscordID,
		&i.DisplayName,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
		&i.Email,
		&i.AppsSuspended,
		&i.DiscordName,
		&i.DiscordAvatar,
		&i.NameFromDiscord,
		&i.Bio,
		&i.AvatarUpdatedAt,
		&i.DiscordBanner,
		&i.DiscordAccent,
		&i.BannerUpdatedAt,
		&i.ShowApps,
		&i.ShowEmail,
		&i.NotifyWebhook,
	)
	return i, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT token_hash, user_id, created_at, expires_at, ip, user_agent FROM sessions WHERE user_id = ? AND expires_at > ? ORDER BY created_at DESC
`

type ListUserSessionsParams struct {
	UserID    int64
	ExpiresAt int64
}

func (q *Queries) ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listUserSessions, arg.UserID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.TokenHash,
			&i.UserID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Ip,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
