// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ssh.sql

package db

import (
	"context"
)

const createSSHKey = `-- name: CreateSSHKey :one
INSERT INTO ssh_keys (user_id, name, public_key, fingerprint, created_at) VALUES (?, ?, ?, ?, ?) RETURNING id, user_id, name, public_key, fingerprint, created_at, last_used_at
`

type CreateSSHKeyParams struct {
	UserID      int64
	Name        string
	PublicKey   string
	Fingerprint string
	CreatedAt   int64
}

func (q *Queries) CreateSSHKey(ctx context.Context, arg CreateSSHKeyParams) (SshKey, error) {
	row := q.db.QueryRowContext(ctx, createSSHKey,
		arg.UserID,
		arg.Name,
		arg.PublicKey,
		arg.Fingerprint,
		arg.CreatedAt,
	)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PublicKey,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteSSHKey = `-- name: DeleteSSHKey :execrows
DELETE FROM ssh_keys WHERE id = ? AND user_id = ?
`

type DeleteSSHKeyParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteSSHKey(ctx context.Context, arg DeleteSSHKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSSHKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSSHKeyByFingerprint = `-- name: GetSSHKeyByFingerprint :one
SELECT id, user_id, name, public_key, fingerprint, created_at, last_used_at FROM ssh_keys WHERE fingerprint = ?
`

func (q *Queries) GetSSHKeyByFingerprint(ctx context.Context, fingerprint string) (SshKey, error) {
	row := q.db.QueryRowContext(ctx, getSSHKeyByFingerprint, fingerprint)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PublicKey,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listSSHKeys = `-- name: ListSSHKeys :many
SELECT id, user_id, name, public_key, fingerprint, created_at, last_used_at FROM ssh_keys WHERE user_id = ? ORDER BY id
`

func (q *Queries) ListSSHKeys(ctx context.Context, userID int64) ([]SshKey, error) {
	rows, err := q.db.QueryContext(ctx, listSSHKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SshKey{}
	for rows.Next() {
		var i SshKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.PublicKey,
			&i.Fingerprint,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSSHKey = `-- name: TouchSSHKey :exec
UPDATE ssh_keys SET last_used_at = ? WHERE id = ?
`

type TouchSSHKeyParams struct {
	LastUsedAt int64
	ID         int64
}

func (q *Queries) TouchSSHKey(ctx context.Context, arg TouchSSHKeyParams) error {
	_, err := q.db.ExecContext(ctx, touchSSHKey, arg.LastUsedAt, arg.ID)
	return err
}
