// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: support.sql

package db

import (
	"context"
	"database/sql"
)

const addTicketMessage = `-- name: AddTicketMessage :one
INSERT INTO support_messages (ticket_id, author_id, body, created_at) VALUES (?, ?, ?, ?) RETURNING id, ticket_id, author_id, body, created_at
`

type AddTicketMessageParams struct {
	TicketID  int64
	AuthorID  sql.NullInt64
	Body      string
	CreatedAt int64
}

func (q *Queries) AddTicketMessage(ctx context.Context, arg AddTicketMessageParams) (SupportMessage, error) {
	row := q.db.QueryRowContext(ctx, addTicketMessage,
		arg.TicketID,
		arg.AuthorID,
		arg.Body,
		arg.CreatedAt,
	)
	var i SupportMessage
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const countWaitingTickets = `-- name: CountWaitingTickets :one
SELECT COUNT(*) FROM support_tickets WHERE status = 'open' AND waiting = 1
`

func (q *Queries) CountWaitingTickets(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWaitingTickets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO support_tickets (author_id, kind, app_id, app_name, subject, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, author_id, kind, app_id, app_name, subject, status, waiting, created_at, updated_at
`

type CreateTicketParams struct {
	AuthorID  int64
	Kind      string
	AppID     sql.NullInt64
	AppName   string
	Subject   string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (SupportTicket, error) {
	row := q.db.QueryRowContext(ctx, createTicket,
		arg.AuthorID,
		arg.Kind,
		arg.AppID,
		arg.AppName,
		arg.Subject,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SupportTicket
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Kind,
		&i.AppID,
		&i.AppName,
		&i.Subject,
		&i.Status,
		&i.Waiting,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT support_tickets.id, support_tickets.author_id, support_tickets.kind, support_tickets.app_id, support_tickets.app_name, support_tickets.subject, support_tickets.status, support_tickets.waiting, support_tickets.created_at, support_tickets.updated_at, users.display_name AS author_name
FROM support_tickets
JOIN users ON users.id = support_tickets.author_id
WHERE support_tickets.id = ?
`

type GetTicketRow struct {
	SupportTicket SupportTicket
	AuthorName    string
}

func (q *Queries) GetTicket(ctx context.Context, id int64) (GetTicketRow, error) {
	row := q.db.QueryRowContext(ctx, getTicket, id)
	var i GetTicketRow
	err := row.Scan(
		&i.SupportTicket.ID,
		&i.SupportTicket.AuthorID,
		&i.SupportTicket.Kind,
		&i.SupportTicket.AppID,
		&i.SupportTicket.AppName,
		&i.SupportTicket.Subject,
		&i.SupportTicket.Status,
		&i.SupportTicket.Waiting,
		&i.SupportTicket.CreatedAt,
		&i.SupportTicket.UpdatedAt,
		&i.AuthorName,
	)
	return i, err
}

const listTicketMessages = `-- name: ListTicketMessages :many
SELECT support_messages.id, support_messages.author_id, support_messages.body, support_messages.created_at,
       COALESCE(users.display_name, '') AS author_name, COALESCE(users.role, '') AS author_role
FROM support_messages
LEFT JOIN users ON users.id = support_messages.author_id
WHERE support_messages.ticket_id = ?
ORDER BY support_messages.id
`

type ListTicketMessagesRow struct {
	ID         int64
	AuthorID   sql.NullInt64
	Body       string
	CreatedAt  int64
	AuthorName string
	AuthorRole string
}

func (q *Queries) ListTicketMessages(ctx context.Context, ticketID int64) ([]ListTicketMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTicketMessages, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketMessagesRow{}
	for rows.Next() {
		var i ListTicketMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorName,
			&i.AuthorRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTickets = `-- name: ListTickets :many
SELECT support_tickets.id, support_tickets.author_id, support_tickets.kind, support_tickets.app_id, support_tickets.app_name, support_tickets.subject, support_tickets.status, support_tickets.waiting, support_tickets.created_at, support_tickets.updated_at, users.display_name AS author_name,
       (SELECT COUNT(*) FROM support_messages m WHERE m.ticket_id = support_tickets.id) AS messages
FROM support_tickets
JOIN users ON users.id = support_tickets.author_id
ORDER BY support_tickets.updated_at DESC
LIMIT 500
`

type ListTicketsRow struct {
	SupportTicket SupportTicket
	AuthorName    string
	Messages      int64
}

func (q *Queries) ListTickets(ctx context.Context) ([]ListTicketsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketsRow{}
	for rows.Next() {
		var i ListTicketsRow
		if err := rows.Scan(
			&i.SupportTicket.ID,
			&i.SupportTicket.AuthorID,
			&i.SupportTicket.Kind,
			&i.SupportTicket.AppID,
			&i.SupportTicket.AppName,
			&i.SupportTicket.Subject,
			&i.SupportTicket.Status,
			&i.SupportTicket.Waiting,
			&i.SupportTicket.CreatedAt,
			&i.SupportTicket.UpdatedAt,
			&i.AuthorName,
			&i.Messages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByAuthor = `-- name: ListTicketsByAuthor :many
SELECT support_tickets.id, support_tickets.author_id, support_tickets.kind, support_tickets.app_id, support_tickets.app_name, support_tickets.subject, support_tickets.status, support_tickets.waiting, support_tickets.created_at, support_tickets.updated_at, users.display_name AS author_name,
       (SELECT COUNT(*) FROM support_messages m WHERE m.ticket_id = support_tickets.id) AS messages
FROM support_tickets
JOIN users ON users.id = support_tickets.author_id
WHERE support_tickets.author_id = ?
ORDER BY support_tickets.updated_at DESC
LIMIT 500
`

type ListTicketsByAuthorRow struct {
	SupportTicket SupportTicket
	AuthorName    string
	Messages      int64
}

func (q *Queries) ListTicketsByAuthor(ctx context.Context, authorID int64) ([]ListTicketsByAuthorRow, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsByAuthor, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketsByAuthorRow{}
	for rows.Next() {
		var i ListTicketsByAuthorRow
		if err := rows.Scan(
			&i.SupportTicket.ID,
			&i.SupportTicket.AuthorID,
			&i.SupportTicket.Kind,
			&i.SupportTicket.AppID,
			&i.SupportTicket.AppName,
			&i.SupportTicket.Subject,
			&i.SupportTicket.Status,
			&i.SupportTicket.Waiting,
			&i.SupportTicket.CreatedAt,
			&i.SupportTicket.UpdatedAt,
			&i.AuthorName,
			&i.Messages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTicketStatus = `-- name: SetTicketStatus :exec
UPDATE support_tickets SET status = ?, updated_at = ? WHERE id = ?
`

type SetTicketStatusParams struct {
	Status    string
	UpdatedAt int64
	ID        int64
}

func (q *Queries) SetTicketStatus(ctx context.Context, arg SetTicketStatusParams) error {
	_, err := q.db.ExecContext(ctx, setTicketStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const touchTicket = `-- name: TouchTicket :exec
UPDATE support_tickets SET waiting = ?, status = 'open', updated_at = ? WHERE id = ?
`

type TouchTicketParams struct {
	Waiting   int64
	UpdatedAt int64
	ID        int64
}

// waiting: the author wrote last; a message reopens a closed ticket.
func (q *Queries) TouchTicket(ctx context.Context, arg TouchTicketParams) error {
	_, err := q.db.ExecContext(ctx, touchTicket, arg.Waiting, arg.UpdatedAt, arg.ID)
	return err
}
